language: node_js
node_js:
    - '0.12'
    - '4.2'
    - '5.5'
install: 'npm install'
script: './scripts/test.sh'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
